### ISSUE TITLE
有些地方看不太明白

### ISSUE THREAD

**Issue by xzxxv** [1260323835/koa2-template#1]
大佬可以留个联系方式交流一下嘛

**Comment by sankeyangshu** [comment]
> 大佬可以留个联系方式交流一下嘛

你好，请问你有什么地方看不明白的？

**Comment by xzxxv** [comment]
> > 大佬可以留个联系方式交流一下嘛
> 
> 你好，请问你有什么地方看不明白的？

就是 最近一直在弄图片上传的  一直就是获取不到files  用的 koa-multer
